% Steinmetz's implementation of refractory violation rate in https://github.com/cortex-lab/sortingQuality/blob/master/core/ISIViolations.m
% He says earlier method (Hill's https://www.jneurosci.org/content/31/24/8699.long) was not correct! https://github.com/rheitz1/Mat_Code/blob/master/UltraMegaSort/quality_measures/rpv_contamination.m
% This methos called as: [fpRate, numViolations] = ISIViolations(spike_times(spike_clusters==clusterIDs(c)), minISI, refDur); 
% with refDur = 0.0015; minISI = 0.0005; in https://github.com/cortex-lab/sortingQuality/blob/master/%2BsqKilosort/isiViolations.m

function [fpRate, numViolations] = refViolations(spikeTrain, neuronType)
% computes an estimated false positive rate of the spikes in the given
% spike train. You probably don't want this to be greater than a few
% percent of the spikes. 
%
% - minISI [sec] = minimum *possible* ISI (based on your cutoff window); likely 1ms
% or so. It's important that you have this number right.
% - refDur [sec] = estimate of the duration of the refractory period; suggested value = 0.002.
% It's also important that you have this number right, but there's no way
% to know... also, if it's a fast spiking cell, you could use a smaller
% value than for regular spiking.
%
% This function was updated on 2023-09-05 by NS to reflect a correction.
% There were two problems: 
% 1) The approximation previously used, which was chosen to avoid getting
% imaginary results, wasn't accurate to the Hill et al paper on which this
% method was based, nor was it accurate to the correct solution to the
% problem
% 2) Hill et al did not have the correct solution to the problem. The Hill
% paper used an expression derived from an earlier work (Meunier et al
% 2003) which had assumed a special case: the "contamination" was itself
% only generated by a single neuron and therefore the contaminating spikes
% themselves had a refractory period. If instead the contaminating spikes
% are generated from a real poisson process (as in the case of electrical
% noise or many nearby neurons generating the contamination), then the
% correct expression is different, as now calculated here. This expression
% is given in Llobet et al. bioRxiv 2022
% (https://www.biorxiv.org/content/10.1101/2022.02.08.479192v1.full.pdf)
%
% In practice, the three methods (the real Hill equation, the method
% previously implemented here, and the correct equation as now implemented)
% return almost identical values for contamination less than ~20%. They
% diverge strongly for 30% or more. 
%
% Bonus: the correct expression no longer returns imaginary values!

    globals;
    
    nTotalSpikes = length(spikeTrain); % total spike count
    nTotalDuration = max(spikeTrain); % duration of recording
    isis = diff(spikeTrain);
    if ~isempty(neuronType) && strcmp(neuronType, NEURON_TYPE_CS) % cos Llobet 2022 uses different time windows for CSs        
        numViolations = sum(isis <= REF_DURATION_CS & isis>MIN_ISI_CS); % number of observed violations
        nRefractoryPeriod = REF_DURATION_CS-MIN_ISI_CS; % tr in the formula in Llobet 2022        
    else
        numViolations = sum(isis <= REF_DURATION & isis>MIN_ISI); % number of observed violations
        nRefractoryPeriod = REF_DURATION-MIN_ISI; % tr in the formula in Llobet 2022
        % Here, the refractory period (tr in the paper or REF_DURATION here) is adjusted to take account of the data recording system's minimum possible 
        % refractory period. E.g. if a system has a sampling rate of fs Hz the closest that two spikes from the same unit 
        % can possibly be is 1/fs (tc in the paper or MIN_ISI here). Hence the refractory period is the expected biological threshold minus this minimum possible threshold.
    end
    
    fpRate =  1 - sqrt(1 - numViolations*nTotalDuration/(nTotalSpikes^2*nRefractoryPeriod));
    % ISI violations identifies unit contamination - a high value indicates a highly contaminated unit. 
    % Despite being a ratio, the contamination can exceed 1 (or become a complex number in the [Llobet] formula). 
    % This is usually due to the contaminant events being correlated with our neuron, and their number is greater than a purely random spike train.

end

%{ 
% everything below is the old behavior of this function. 


totalRate = length(spikeTrain)/spikeTrain(end);
numViolations = sum(diff(spikeTrain) <= refDur);

% Spikes occurring under the minimum ISI are by definition false positives;
% their total rate relative to the rate of the neuron overall gives the
% estimated false positive rate.
% NOTE: This does not use the equation from Dan Hill's paper (see below)
% but instead uses the equation from his UltraMegaSort
violationTime = 2*length(spikeTrain)*(refDur-minISI); % total time available for violations - 
                                                    % there is an available
                                                    % window of length
                                                    % (refDur-minISI) after
                                                    % each spike.
violationRate = numViolations/violationTime;
fpRate = violationRate/totalRate;

if fpRate>1
    % it is nonsense to have a rate >1, however having such large rates
    % does tell you something interesting, namely that the assumptions of
    % this analysis are failing!
    fpRate = 1; 
end


% Here is with Dan Hill's equation (J. Neurosci, 2012)
%  NOTE: actually, this method will return imaginary results for large-ish
%  numbers of violations. 
% tauR = refDur;
% tauC = minISI;
% T = spikeTrain(end);
% N = length(spikeTrain);
% R = sum(diff(spikeTrain) <= tauR);
% 
% k = 2*(tauR-tauC)*N^2;
% rts = roots([k -k R*T]);
% 
% fpRate = min(rts);
% numViolations = R;
end
%}