Paths = { ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1694\1694_240306_hab3_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1694\1694_240308_day1_noClick_g3'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1694\1694_240312_day2_noClick_click_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1694\1694_240315_day3_Allclick_Tone_NoTone_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1694\1694_240318_day4_Allclick_ToneOff_noNpx_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1694\1694_240319_day5_Allclick_ToneOff_noNpx_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1694\1694_240320_day6_Allclick_ToneOff_noNpx_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1694\1694_240320_day7_Allclick_ToneOff_NoTone_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1694\1694_240325_day8_tone_train_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1694\1694_240326_day9_tone_train_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1694\1694_240328_day10_tone_trained_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1694\1694_240401_day11_tone_train_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1694\1694_240402_day12_tone_train_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1694\1694_240403_day13_tone_train_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1694\1694_240405_day14_tone_train_noNpx_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1694\1694_240408_day15_tone_train_noNpx_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1694\1694_240409_day16_tone_train_noNpx_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1694\1694_240410_day17_tone_train_noNpx_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1694\1694_240410_day18_test_Analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1694\1694_240415_day19_train_Analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1694\1694_240416_day20_train_Analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1694\1694_240415_day19_train_Analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1694\1694_240418_day22_train_Analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1694\1694_240419_day23_test_Analysis'; ...
    ... % 1695 
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1695\1695_240430_day1_silentReward_unpairedClick_g0_analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1695\1695_240501_day2_silentReward_pairedClick_unpairedTone_g0_analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1695\1695_240502_day3_pairedClick_silentReward_unpairedTone_g0_analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1695\1695_240503_day4_allAudibleRwd_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1695\1695_240506_day5_allAudibleRwd_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1695\1695_240507_day6_test_g0_analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1695\1695_240508_day7_naive_g0_analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1695\1695_240509_day8_trainWnpx_g0_analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1695\1695_240510_day9_trainNoNpx_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1695\1695_240513_day10_trainNoNpx_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1695\1695_240514_day11_trainWnpx_g0_analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1695\1695_240515_day12_trainWnpx_g0_analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1695\1695_240516_day13_trainWnpx_g0_analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1695\1695_240517_day14_trainWnpx_g0_analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1695\1695_240520_day15_trainNonnpx_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1695\1695_240521_day16_trainWnpx_g0_analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1695\1695_240522_day17_trainNonpx_g2'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1695\1695_240523_day18_NoxpyxTrain_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1695\1695_240524_day19_Wnpyx_g0_analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1695\1695_240528_day20_Nonpyx_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1695\1695_240529_day21_testNpx_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1695\1695_240530_day22_trainNonpx_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1695\1695_240531_day23_testNpx_g0_analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1695\1695_240603_day24_trainNonpx_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1695\1695_240604_day25_testNpx_g0_analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1695\1695_240605_day26_testNpx_g0_analysis'; ...
    ... % 1697
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1697\1697_240522_day1_silentRwd_g1_analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1697\1697_240523_day2_g0_analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1697\1697_240528_day3_g0_analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1697\1697_240529_day4_g0_analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1697\1697_240531_day5_trainNonpx_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1697\1697_240603_day6_trainNpx_g0_analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1697\1697_240605_day7_g0_analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1697\1697_240613_day8_noNpx_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1697\1697_240614_day9_Npx_g0_analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1697\1697_240617_day10_Npx_g0_analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1697\1697_240618_day11_Npx_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1697\1697_240620_day12_Npx_g0_analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1697\1697_240624_day13_noNpx_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1697\1697_240625_day14_noNpx_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1697\1697_240626_day15_Npx_g0_analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1697\1697_240627_day16_noNpx_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1697\1697_240628_day17_Npx_b_g0_analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1697\1697_240701_day18_Npx_g0_analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1697\240708_1697_day19_trainNoNpx_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1697\240709_1697_day20_supercat_Analysis\C4'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1697\240710_1697_day21_noNpx_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1697\240711_1697_day22_Npx_g0_analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1697\240712_1697_day23_noNpx_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1697\240715_1697_day24_noNpx_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1697\240716_1697_day25_Npx_g0_analysis'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1697\240718_1697_day26_Npx_g0_analysis'; ...
    ... % all the day 1 mice
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1670\1670_230126_g1'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1665_221214_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1666_211215_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1672\BW\supercat_1672_230209_g1'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1674\1674_230214_g1'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1676\1676_230329_g1'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1677\1677_230405_g1'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDay1\1678\1678_230413_g1'; ...
    ... % 1667
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDayN\1667\230106_1667_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDayN\1667\230109_1667_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDayN\1667\230110_1667_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDayN\1667\230111_1667_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDayN\1667\230113_1667_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDayN\1667\230118_1667_g1'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDayN\1667\230119_1667_g2'; ...
    ... % 1668
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDayN\1668\230106_1668_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDayN\1668\230109_1668_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDayN\1668\230110_1668_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDayN\1668\230111_1668_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDayN\1668\1668_011223_g1'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDayN\1668\230117_1668_g1'; ...
    ...  % 1669
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDayN\1669\230106_1669_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDayN\1669\230109_1669_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDayN\1669\230110_1669_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDayN\1669\230113_16679_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDayN\1669\230122_1669_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDayN\1669\230123_1669_g2'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDayN\1669\230122_1669_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDayN\1669\1669_230125_g1'; ...
    ...   % 1673
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDayN\1673\1673_230210_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDayN\1673\1673_230213_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDayN\1673\1673_230214_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDayN\1673\1673_230215_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDayN\1673\1673_230216_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDayN\1673\1673_230217\supercat\BW\supercat_1673_230217_g1'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDayN\1673\1673_230220_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\AuditoryDayN\1673\1673_230221_g1'; ...
    ... % 1653
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\auditoryCS1653\1653_220610_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\auditoryCS1653\1653_220613_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\auditoryCS1653\1653_220615_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\auditoryCS1653\1653_220622_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\auditoryCS1653\1653_220623_g0'; ...
    '\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\NeuropixelsAnalysis\auditoryCS1653\1653_220624_g2'; ...
    };

skips = [70; 80; 111]; % some of the paths need special attention because they were concatenated;
missings = [6; 7; 63; 64; 66];  % these recordings have missing rotary information, I think becaus of loose wires
for p = 1:length(Paths)
    if ~ismember (p, skips)
        if ~ismember (p, missings)
            cd(Paths{p})
            [SpeedTimes, SpeedValues] = QuadratureDecoderFast();
            SpeedTimes = SpeedTimes.';
            [RunMetaData, Index_stay_cell, Index_move_cell, Index_forwardrun_cell, still_TGA, still_TGB, move_TGA, move_TGB] = find_behavStatesMEH(SpeedTimes, SpeedValues);
            % for n = 1:length(still_TGA) THIS CAN BE DONE LATER AFTER CONCATENATION
            % if ~isempty(find(still_TGA(n) < AllLicks & AllLicks < still_TGB(n)))
            % qsc_TGA(n) = NaN;
            % qsc_TGB(n) = NaN;
            % else
            % qsc_TGA(n) = still_TGA(n);
            % qsc_TGB(n) = still_TGB(n);
            % end
            % end
            % qsc_TGA = rmmissing(qsc_TGA);
            % qsc_TGB = rmmissing(qsc_TGB);
            
            RunningStruct.SpeedTimes = SpeedTimes;
            RunningStruct.SpeedValues = SpeedValues;
            RunningStruct.move_TGA = move_TGA;
            RunningStruct.move_TGB = move_TGB;
            RunningStruct.still_TGA = still_TGA;
            RunningStruct.still_TGB = still_TGB;
            RunningStruct.RunMetaData = RunMetaData;
            RunningStruct.loc = what().path;
            %     load BehavorWorkspace.mat
            %     BehavList(p).loc = BehaviorList.loc;
            %     BehavList(p).mouse = BehaviorList.mouse;
            %     BehavList(p).date = BehaviorList.date ;
            %     BehavList(p).day = BehaviorList.day;
            %     BehavList(p).AllLicks = BehaviorList.AllLicks;
            %     BehavList(p).ToneTimes = BehaviorList.ToneTimes;
            %     BehavList(p).JuiceTimes = BehaviorList.JuiceTimes;
            %     BehavList(p).JuiceTimes_clk = BehaviorList.JuiceTimes_clk;
            %     BehavList(p).JuiceTimes_sil = BehaviorList.JuiceTimes_sil;
            %     BehavList(p).NoJuiceClk = BehaviorList.NoJuiceClk;
            BehavList(p).RunningStruct = RunningStruct;
        end
    end
end
cd('\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\CCconcat\AllBehaviorOnlyBehavior');
% save BehavList BehavList % This was done and I don't want it to be redone accidentally
% output saved as BehavListRotEnc1.mat 

% all of these files have had the local analysisCodeBehavior.m run & saved
% the workspace with these BehavList parameters
for p = 1:length(Paths)
    if ~ismember (p, skips)
        cd(Paths{p})
    load('BehavorWorkspace.mat', 'BehaviorList')
    BehavList(p).loc = BehaviorList.loc;
    BehavList(p).mouse = BehaviorList.mouse;
    BehavList(p).date = BehaviorList.date ;
    BehavList(p).day = BehaviorList.day;
    BehavList(p).AllLicks = BehaviorList.AllLicks;
    BehavList(p).ToneTimes = BehaviorList.ToneTimes;
    BehavList(p).JuiceTimes = BehaviorList.JuiceTimes;
    BehavList(p).JuiceTimes_clk = BehaviorList.JuiceTimes_clk;
    BehavList(p).JuiceTimes_sil = BehaviorList.JuiceTimes_sil;
    BehavList(p).NoJuiceClk = BehaviorList.NoJuiceClk;
% clear all
    end
end
cd('\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\CCconcat\AllBehaviorOnlyBehavior');
save BehavList BehavList

% now we deal with the skips, that are concatenations of 2 or 3 SpikeGlx
% recordings (due to a failure of SpikeGlx, nesessitating a restart in the
% middle of a recording).
skIndex = 1; %skips index
p = skips(skIndex);
cd(Paths{p})
load('Workspace.mat', 'AllLicksAdj');
load('Workspace.mat', 'ToneTimesAdj');
load('Workspace.mat', 'JuiceTimesAdj');
load('Workspace.mat', 'JuiceTimes_clk');
load('Workspace.mat', 'JuiceTimes_sil');
load('Workspace.mat', 'RunningStruct');
NoJuiceClk = [];

BehavList(p).loc = what().path;
BehavList(p).mouse = 1697;
BehavList(p).date = 240709;
BehavList(p).day = 20;
BehavList(p).AllLicks = AllLicksAdj;
BehavList(p).ToneTimes = ToneTimesAdj;
BehavList(p).JuiceTimes = JuiceTimesAdj;
BehavList(p).JuiceTimes_clk = JuiceTimes_clk;
BehavList(p).JuiceTimes_sil = JuiceTimes_sil;
BehavList(p).NoJuiceClk = NoJuiceClk;
BehavList(p).RunningStruct = RunningStruct;


skIndex = 2; %skips index
p = skips(skIndex);
cd(Paths{p})
clear AllLicksAdj JuiceTimes_clk JuiceTimes_sil JuiceTimesAdj NoJuiceClk RunningStruct ToneTimesAdj

load('ExpertLabels.mat', 'AllLicksAdj');
load('ExpertLabels.mat', 'ToneTimesAdj');
load('ExpertLabels.mat', 'JuiceTimesAdj');
load('RunningStruct.mat', 'RunningStruct');
NoJuiceClk = [];
JuiceTimes_sil = [];

BehavList(p).loc = what().path;
BehavList(p).mouse = 1672;
BehavList(p).date = 230209;
BehavList(p).day = 7;
BehavList(p).AllLicks = AllLicksAdj;
BehavList(p).ToneTimes = ToneTimesAdj;
BehavList(p).JuiceTimes = JuiceTimesAdj;
BehavList(p).JuiceTimes_clk = JuiceTimesAdj;
BehavList(p).JuiceTimes_sil = JuiceTimes_sil;
BehavList(p).NoJuiceClk = NoJuiceClk;
BehavList(p).RunningStruct = RunningStruct;


skIndex = 3; %skips index
p = skips(skIndex);
cd(Paths{p})
clear AllLicksAdj JuiceTimes_clk JuiceTimes_sil JuiceTimesAdj NoJuiceClk RunningStruct ToneTimesAdj

load('ExpertLabel2.mat', 'AllLicksAdj');
load('ExpertLabel2.mat', 'ToneTimesAdj');
load('ExpertLabel2.mat', 'JuiceTimesAdj');
load('RunningStruct.mat', 'RunningStruct');
NoJuiceClk = [];
JuiceTimes_sil = [];

BehavList(p).loc = what().path;
BehavList(p).mouse = 1673;
BehavList(p).date = 230217;
BehavList(p).day = 12;
BehavList(p).AllLicks = AllLicksAdj;
BehavList(p).ToneTimes = ToneTimesAdj;
BehavList(p).JuiceTimes = JuiceTimesAdj;
BehavList(p).JuiceTimes_clk = JuiceTimesAdj;
BehavList(p).JuiceTimes_sil = JuiceTimes_sil;
BehavList(p).NoJuiceClk = NoJuiceClk;
BehavList(p).RunningStruct = RunningStruct;

cd('\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\CCconcat\AllBehaviorOnlyBehavior');
save BehavList BehavList


%%% recreate TrialStruct and other pre-calcs
% %labeled trials
for n = 1:length(BehavList)
 [BehavList(n).TrialStruct, ~, ~] = TrialStruct_JuiceToneClick(BehavList(n).JuiceTimes_sil, BehavList(n).JuiceTimes_clk, BehavList(n).NoJuiceClk, BehavList(n).ToneTimes);
end

% %remake all outcomes with OutcomesAndOtherMetics 
 [BehavList] = OutcomesAndOtherMetrics(BehavList, .15);
%
% %fix RunningStruct to include still with 
% for R = 1:36
% [~, ~, ~, ~, BehavList_(R).RunningStruct.still_TGA, BehavList_(R).RunningStruct.still_TGB, ~, ~] = find_behavStatesMEH(BehavList_(R).RunningStruct.SpeedTimesAdj, BehavList_(R).RunningStruct.SpeedValues);
% end
for n =1:length(BehavList)
    if BehavList(n).PredPerc_potP > .45 & BehavList(n).MissPerc_potP < .25
        BehavList(n).TrainBoo = 1;
        BehavList(n).day
    else
        BehavList(n).TrainBoo = 0;
    end
end

cd('\\duhs-user-nc1.dhe.duke.edu\dusom_glickfeldlab\All_Staff\home\marie\CCconcat\AllBehaviorOnlyBehavior');
save BehavList BehavList
