import os

import numpy as np


def initialize():
    global TSNE_FEATURE_SIZE, pathToParentRec, ALL_RECORDINGS_FILE, TSNE_RESULT_FILE, PCA_RESULT_FILE, LASSO_RESULT_FILE, MLR_RESULT_FILE, DATA_FILE_NAME, dateOfRecording, LOCAL, PCA_DIM_SIZE,\
        TSNE_PERPLEXITY, TSNE_XY_LIM, EDGES_HOLD, EDGES_RELEASE, EDGES_VIS_STIM, PLOT_EDGES_HOLD, PLOT_EDGES_RELEASE, PLOT_EDGES_VIS_STIM, \
        PRE_TIME_HOLD, POST_TIME_HOLD, PRE_TIME_RELEASE, POST_TIME_RELEASE, PRE_TIME_VIS_STIM, POST_TIME_VIS_STIM, \
        PLOT_PRE_TIME_HOLD, PLOT_POST_TIME_HOLD, PLOT_PRE_TIME_RELEASE, PLOT_POST_TIME_RELEASE, PLOT_PRE_TIME_VIS_STIM, PLOT_POST_TIME_VIS_STIM, \
        NEURON_TYPE_MF, NEURON_TYPE_SS, NEURON_TYPE_CS, NEURON_TYPE_DCS, NEURON_TYPE_BC_SC, NEURON_TYPE_GoC, NEURON_TYPE_UBC, NEURON_TYPES, NEURON_TYPE_UNKNOWN, \
        HIT_OUTCOME, FA_OUTCOME, MISS_OUTCOME

    PRE_TIME_HOLD = 2
    POST_TIME_HOLD = 2
    PRE_TIME_RELEASE = 2
    POST_TIME_RELEASE = 2
    PRE_TIME_VIS_STIM = 2
    POST_TIME_VIS_STIM = 2
    BIN_SIZE_PSTH = 0.001

    PLOT_PRE_TIME_HOLD = .5
    PLOT_POST_TIME_HOLD = .5
    PLOT_PRE_TIME_RELEASE = .5
    PLOT_POST_TIME_RELEASE = .5
    PLOT_PRE_TIME_VIS_STIM = .5
    PLOT_POST_TIME_VIS_STIM = .5

    EDGES_HOLD = np.arange(-PRE_TIME_HOLD-BIN_SIZE_PSTH,POST_TIME_HOLD+BIN_SIZE_PSTH,BIN_SIZE_PSTH)
    EDGES_RELEASE = np.arange(-PRE_TIME_RELEASE-BIN_SIZE_PSTH,POST_TIME_RELEASE+BIN_SIZE_PSTH,BIN_SIZE_PSTH)
    EDGES_VIS_STIM = np.arange(-PRE_TIME_VIS_STIM-BIN_SIZE_PSTH,POST_TIME_VIS_STIM+BIN_SIZE_PSTH,BIN_SIZE_PSTH)

    PLOT_EDGES_HOLD = np.arange(-PLOT_PRE_TIME_HOLD - BIN_SIZE_PSTH, PLOT_POST_TIME_HOLD + BIN_SIZE_PSTH, BIN_SIZE_PSTH)
    PLOT_EDGES_RELEASE = np.arange(-PLOT_PRE_TIME_RELEASE - BIN_SIZE_PSTH, PLOT_POST_TIME_RELEASE + BIN_SIZE_PSTH, BIN_SIZE_PSTH)
    PLOT_EDGES_VIS_STIM = np.arange(-PLOT_PRE_TIME_VIS_STIM - BIN_SIZE_PSTH, PLOT_POST_TIME_VIS_STIM + BIN_SIZE_PSTH, BIN_SIZE_PSTH)

    LOCAL = True
    TSNE_FEATURE_SIZE = 402
    PCA_DIM_SIZE = 50
    TSNE_PERPLEXITY = 40
    TSNE_XY_LIM = 20

    if ~LOCAL:
        PCA_DIM_SIZE = 50

    if os.name == 'nt':  # Windows
        pathToParentRec = 'S:/Neuropixels/test_data/pooled/'
    else:  # Ubuntu
        #pathToParentRec = '/home/sot5@dhe.duke.edu/IsilonSevgi/Neuropixels/test_data/pooled/'
        pathToParentRec = '/mnt/IsilonPerm/Neuropixels/test_data/pooled/'

    dateOfRecording = '20230210_' #'20230131_' #'20230210_'
    DATA_FILE_NAME = 'unitsAndVars_'  # if dateOfRecording is empty, loads all recordings,  if not ('unitsAndVars_' + dateOfRecording), loads only that recording

    ALL_RECORDINGS_FILE = pathToParentRec + 'allData/allRecordings.mat'  # allRecordingsSmall
    TSNE_RESULT_FILE = pathToParentRec + 'tSNEResults/'
    PCA_RESULT_FILE = pathToParentRec + 'pcaResults/'
    MLR_RESULT_FILE = pathToParentRec + 'multinomialLR/'
    LASSO_RESULT_FILE = TSNE_RESULT_FILE = pathToParentRec + 'lassoResults/'

    NEURON_TYPE_MF = 'MF'
    NEURON_TYPE_SS = 'PC SS'
    NEURON_TYPE_CS = 'PC CS'
    NEURON_TYPE_DCS = 'PC DCS'
    NEURON_TYPE_BC_SC = 'BC or SC'
    NEURON_TYPE_GoC = 'GoC'
    NEURON_TYPE_UBC = 'UBC'
    NEURON_TYPE_UNKNOWN = 'Unknown'
    NEURON_TYPES = np.array([NEURON_TYPE_MF, NEURON_TYPE_SS, NEURON_TYPE_CS, NEURON_TYPE_DCS, NEURON_TYPE_BC_SC, NEURON_TYPE_GoC, NEURON_TYPE_UBC, NEURON_TYPE_UNKNOWN])

    HIT_OUTCOME = 1
    FA_OUTCOME = 2
    MISS_OUTCOME = 3