function [spikeRatesHoldRandomAll, spikeRatesHoldFixedAll, spikeRatesHoldRandomHFM, spikeRatesHoldFixedHFM, spikeRatesReleaseRandomAll, spikeRatesReleaseFixedAll, ...
    spikeRatesReleaseRandomHFM, spikeRatesReleaseFixedHFM, spikeRatesTargetRandomAll, spikeRatesTargetFixedAll, spikeRatesTargetRandomHFM, spikeRatesTargetFixedHFM, ...
    responseTypeHoldFixedAll, responseTypeHoldFixedHFM, responseTypeReleaseFixedAll, responseTypeReleaseFixedHFM, responseTypeTargetFixedAll, responseTypeTargetFixedHFM] = ...
    plotRasterPSTH(unit, unitCategory, preHoldTime, fixedHoldStartsAtTrial, leverHoldTimes, leverReleaseTimesGLX, targetStimTimesGLX, baselineStimTimesGLX, arrStimTurnedOnTrials, allTrials, arrHitTrials, arrFaTrials, arrMissTrials)

        globals; 

        [spikeTimeAlignedToLeverHoldAll, spikeTimeAlignedToLeverReleaseAll, spikeTimeAlignedToTargetVisStimAll, spikeTimeAlignedToBaselineVisStimAll, ...
        spikeTimeofTrialAlignedToLeverReleaseAll, spikeTimeofTrialwITIAlignedToLeverReleaseAll, leverHoldTimesAlignedToLeverReleaseAll,...
        leverHoldTimesAlignedToTargetVisStimAll, leverReleaseTimesAlignedToTargetVisStimAll, leverReleaseTimesAlignedToBaselineVisStimAll, targetVisStimAlignedToLeverHoldAll, targetVisStimAlignedToLeverReleaseAll, ...
        baselineVisStimAlignedToLeverReleaseAll, fixedHoldStartsAtRelativeTrialAll, allTrialCount] = chunkAlignSpikeTimes(unit.spikeTimesSecs, preHoldTime, fixedHoldStartsAtTrial, leverHoldTimes, leverReleaseTimesGLX, targetStimTimesGLX, baselineStimTimesGLX, arrStimTurnedOnTrials, allTrials);
    
        [spikeTimeAlignedToLeverHoldHit, spikeTimeAlignedToLeverReleaseHit, spikeTimeAlignedToTargetVisStimHit, spikeTimeAlignedToBaselineVisStimHit, ...
        spikeTimeofTrialAlignedToLeverReleaseHit, spikeTimeofTrialwITIAlignedToLeverReleaseHit, leverHoldTimesAlignedToLeverReleaseHit,...
        leverHoldTimesAlignedToTargetVisStimHit, leverReleaseTimesAlignedToTargetVisStimHit, leverReleaseTimesAlignedToBaselineVisStimHit, targetVisStimAlignedToLeverHoldHit, targetVisStimAlignedToLeverReleaseHit, ...
        baselineVisStimAlignedToLeverReleaseHit, fixedHoldStartsAtRelativeTrialHit, ~] = chunkAlignSpikeTimes(unit.spikeTimesSecs, preHoldTime, fixedHoldStartsAtTrial, leverHoldTimes, leverReleaseTimesGLX, targetStimTimesGLX, baselineStimTimesGLX, arrStimTurnedOnTrials, arrHitTrials);
    
        [spikeTimeAlignedToLeverHoldFa, spikeTimeAlignedToLeverReleaseFa, spikeTimeAlignedToTargetVisStimFa, spikeTimeAlignedToBaselineVisStimFa, ...
        spikeTimeofTrialAlignedToLeverReleaseFa, spikeTimeofTrialwITIAlignedToLeverReleaseFa, leverHoldTimesAlignedToLeverReleaseFa,...
        leverHoldTimesAlignedToTargetVisStimFa, leverReleaseTimesAlignedToTargetVisStimFa, leverReleaseTimesAlignedToBaselineVisStimFa, targetVisStimAlignedToLeverHoldFa, targetVisStimAlignedToLeverReleaseFa, ...
        baselineVisStimAlignedToLeverReleaseFa, fixedHoldStartsAtRelativeTrialFa, ~] = chunkAlignSpikeTimes(unit.spikeTimesSecs, preHoldTime, fixedHoldStartsAtTrial, leverHoldTimes, leverReleaseTimesGLX, targetStimTimesGLX, baselineStimTimesGLX, arrStimTurnedOnTrials, arrFaTrials);
    
        [spikeTimeAlignedToLeverHoldMiss, spikeTimeAlignedToLeverReleaseMiss, spikeTimeAlignedToTargetVisStimMiss, spikeTimeAlignedToBaselineVisStimMiss, ...
        spikeTimeofTrialAlignedToLeverReleaseMiss, spikeTimeofTrialwITIAlignedToLeverReleaseMiss, leverHoldTimesAlignedToLeverReleaseMiss,...
        leverHoldTimesAlignedToTargetVisStimMiss, leverReleaseTimesAlignedToTargetVisStimMiss, leverReleaseTimesAlignedToBaselineVisStimMiss, targetVisStimAlignedToLeverHoldMiss, targetVisStimAlignedToLeverReleaseMiss, ...
        baselineVisStimAlignedToLeverReleaseMiss, fixedHoldStartsAtRelativeTrialMiss, ~] = chunkAlignSpikeTimes(unit.spikeTimesSecs, preHoldTime, fixedHoldStartsAtTrial, leverHoldTimes, leverReleaseTimesGLX, targetStimTimesGLX, baselineStimTimesGLX, arrStimTurnedOnTrials, arrMissTrials);
    
        plotRasterLeverVisStim(unit.id, unitCategory, unit.neuronType, unit.layer, unit.ch, allTrialCount, spikeTimeAlignedToLeverHoldAll, spikeTimeAlignedToLeverReleaseAll, spikeTimeAlignedToTargetVisStimAll, spikeTimeAlignedToBaselineVisStimAll, ...
            targetVisStimAlignedToLeverHoldAll, targetVisStimAlignedToLeverReleaseAll, baselineVisStimAlignedToLeverReleaseAll, leverHoldTimesAlignedToTargetVisStimAll, leverReleaseTimesAlignedToTargetVisStimAll, leverReleaseTimesAlignedToBaselineVisStimAll, ...
            fixedHoldStartsAtRelativeTrialAll, leverHoldTimes, leverReleaseTimesGLX, targetStimTimesGLX, baselineStimTimesGLX, arrStimTurnedOnTrials, allTrials, 'All');
        
        plotRasterLeverVisStim(unit.id, unitCategory, unit.neuronType, unit.layer, unit.ch, allTrialCount, spikeTimeAlignedToLeverHoldHit, spikeTimeAlignedToLeverReleaseHit, spikeTimeAlignedToTargetVisStimHit, spikeTimeAlignedToBaselineVisStimHit, ...
            targetVisStimAlignedToLeverHoldHit, targetVisStimAlignedToLeverReleaseHit, baselineVisStimAlignedToLeverReleaseHit, leverHoldTimesAlignedToTargetVisStimHit, leverReleaseTimesAlignedToTargetVisStimHit, leverReleaseTimesAlignedToBaselineVisStimHit, ...
            fixedHoldStartsAtRelativeTrialHit, leverHoldTimes, leverReleaseTimesGLX, targetStimTimesGLX, baselineStimTimesGLX, arrStimTurnedOnTrials, arrHitTrials, 'Hit');
        
        plotRasterLeverVisStim(unit.id, unitCategory, unit.neuronType, unit.layer, unit.ch, allTrialCount, spikeTimeAlignedToLeverHoldFa, spikeTimeAlignedToLeverReleaseFa, spikeTimeAlignedToTargetVisStimFa, spikeTimeAlignedToBaselineVisStimFa, ...
            targetVisStimAlignedToLeverHoldFa, targetVisStimAlignedToLeverReleaseFa, baselineVisStimAlignedToLeverReleaseFa, leverHoldTimesAlignedToTargetVisStimFa, leverReleaseTimesAlignedToTargetVisStimFa, leverReleaseTimesAlignedToBaselineVisStimFa, ...
            fixedHoldStartsAtRelativeTrialFa, leverHoldTimes, leverReleaseTimesGLX, targetStimTimesGLX, baselineStimTimesGLX, arrStimTurnedOnTrials, arrFaTrials, 'Fa');

        plotRasterLeverVisStim(unit.id, unitCategory, unit.neuronType, unit.layer, unit.ch, allTrialCount, spikeTimeAlignedToLeverHoldMiss, spikeTimeAlignedToLeverReleaseMiss, spikeTimeAlignedToTargetVisStimMiss, spikeTimeAlignedToBaselineVisStimMiss, ...
            targetVisStimAlignedToLeverHoldMiss, targetVisStimAlignedToLeverReleaseMiss, baselineVisStimAlignedToLeverReleaseMiss, leverHoldTimesAlignedToTargetVisStimMiss, leverReleaseTimesAlignedToTargetVisStimMiss, leverReleaseTimesAlignedToBaselineVisStimMiss, ...
            fixedHoldStartsAtRelativeTrialMiss, leverHoldTimes, leverReleaseTimesGLX, targetStimTimesGLX, baselineStimTimesGLX, arrStimTurnedOnTrials, arrMissTrials, 'Miss');
           
%         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% PSTHs %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%         [spikeRatesHoldRandomAll, spikeRatesHoldFixedAll, responseTypeHoldFixedAll] = plotPSTH(unit.id, unitCategory, unit.neuronType, unit.layer, unit.ch, allTrialCount, {spikeTimeAlignedToLeverHoldAll}, {fixedHoldStartsAtRelativeTrialAll}, {targetVisStimAlignedToLeverHoldAll}, {}, ...
%             PRE_TIME_HOLD, POST_TIME_HOLD, EDGES_HOLD, 'Lever Hold aligned (Target Stim red marked)', 'Lever Hold aligned', 'leverHoldAligned', {'All'}, {'r'}, {ALL_COLOR});
%         [spikeRatesHoldRandomHFM, spikeRatesHoldFixedHFM, responseTypeHoldFixedHFM] = plotPSTH(unit.id, unitCategory, unit.neuronType, unit.layer, unit.ch, allTrialCount, {spikeTimeAlignedToLeverHoldHit, spikeTimeAlignedToLeverHoldFa, spikeTimeAlignedToLeverHoldMiss}, ...
%             {fixedHoldStartsAtRelativeTrialHit, fixedHoldStartsAtRelativeTrialFa, fixedHoldStartsAtRelativeTrialMiss}, ...
%             {targetVisStimAlignedToLeverHoldHit, targetVisStimAlignedToLeverHoldFa, targetVisStimAlignedToLeverHoldMiss}, {}, PRE_TIME_HOLD, POST_TIME_HOLD, EDGES_HOLD, ...
%             'Lever Hold aligned (Target Stim red marked)', 'Lever Hold aligned', 'leverHoldAligned', {'Hit','Fa','Miss'}, {'r'}, {HIT_COLOR, FA_COLOR, MISS_COLOR});
%                                 
%         [spikeRatesReleaseRandomAll, spikeRatesReleaseFixedAll, responseTypeReleaseFixedAll] = plotPSTH(unit.id, unitCategory, unit.neuronType, unit.layer, unit.ch, allTrialCount, {spikeTimeAlignedToLeverReleaseAll}, {fixedHoldStartsAtRelativeTrialAll}, {targetVisStimAlignedToLeverReleaseAll}, {}, ... 
%             PRE_TIME_RELEASE, POST_TIME_RELEASE, EDGES_RELEASE, 'Lever Release aligned (Target Stim red marked)', 'Lever Release aligned', 'leverReleaseAligned', {'All'}, {'r'}, {ALL_COLOR}); % (Target Stim red marked)
%         [spikeRatesReleaseRandomHFM, spikeRatesReleaseFixedHFM, responseTypeReleaseFixedHFM] = plotPSTH(unit.id, unitCategory, unit.neuronType, unit.layer, unit.ch, allTrialCount, {spikeTimeAlignedToLeverReleaseHit, spikeTimeAlignedToLeverReleaseFa, spikeTimeAlignedToLeverReleaseMiss}, ...
%             {fixedHoldStartsAtRelativeTrialHit, fixedHoldStartsAtRelativeTrialFa, fixedHoldStartsAtRelativeTrialMiss}, ...
%             {targetVisStimAlignedToLeverReleaseHit, targetVisStimAlignedToLeverReleaseFa, targetVisStimAlignedToLeverReleaseMiss}, {}, PRE_TIME_RELEASE, POST_TIME_RELEASE, EDGES_RELEASE, ... % targetVisStimAlignedToLeverReleaseHit, targetVisStimAlignedToLeverReleaseFa, targetVisStimAlignedToLeverReleaseMiss
%             'Lever Release aligned (Target Stim red marked)', 'Lever Release aligned', 'leverReleaseAligned', {'Hit','Fa','Miss'}, {'r'}, {HIT_COLOR, FA_COLOR, MISS_COLOR}); %  (Target Stim red marked)
% 
%         [spikeRatesTargetRandomAll, spikeRatesTargetFixedAll, responseTypeTargetFixedAll] = plotPSTH(unit.id, unitCategory, unit.neuronType, unit.layer, unit.ch, allTrialCount, {spikeTimeAlignedToTargetVisStimAll}, {fixedHoldStartsAtRelativeTrialAll}, {leverHoldTimesAlignedToTargetVisStimAll}, {leverReleaseTimesAlignedToTargetVisStimAll}, ...
%             PRE_TIME_VIS_STIM, POST_TIME_VIS_STIM, EDGES_VIS_STIM, 'Target Stim aligned (Hold(blue) and Release(magenta) marked)', 'Target Stim aligned', 'targetStimAligned', {'All'}, {'b', 'm'}, {ALL_COLOR});
%                                                                                                                                         % don't send spikeTimeAlignedToTargetVisStimFa, no need for target stim aligned trials cos many Fa trials normally should not have target stim
%         [spikeRatesTargetRandomHFM, spikeRatesTargetFixedHFM, responseTypeTargetFixedHFM] = plotPSTH(unit.id, unitCategory, unit.neuronType, unit.layer, unit.ch, allTrialCount, {spikeTimeAlignedToTargetVisStimHit, spikeTimeAlignedToTargetVisStimMiss}, ... 
%             {fixedHoldStartsAtRelativeTrialHit, fixedHoldStartsAtRelativeTrialMiss}, ...
%             {leverHoldTimesAlignedToTargetVisStimHit, leverHoldTimesAlignedToTargetVisStimMiss}, ...
%             {leverReleaseTimesAlignedToTargetVisStimHit, leverReleaseTimesAlignedToTargetVisStimMiss}, ...
%             PRE_TIME_VIS_STIM, POST_TIME_VIS_STIM, EDGES_VIS_STIM, ...
%             'Target Stim aligned (Hold(blue) and Release (magenta) marked)', 'Target Stim aligned', 'targetStimAligned', {'Hit', 'Miss'}, {'b', 'm'}, {HIT_COLOR, MISS_COLOR}); % 'Fa',
%         
%         % No NEED to Baseline Stim aligned PSTH right now! Maybe in future
% %         plotPSTH(unit.id, unit.neuronType, unit.layer, unit.ch, allTrialCount, {spikeTimeAlignedToBaselineVisStimAll}, {fixedHoldStartsAtRelativeTrialAll}, {leverReleaseTimesAlignedToBaselineVisStimAll}, {}, ...
% %             PRE_TIME_VIS_STIM, POST_TIME_VIS_STIM, EDGES_VIS_STIM, 'Baseline Stim aligned (Lever Release blue marked)', 'Baseline Stim aligned', 'baselineStimAligned', {'All'}, {'b'}, {ALL_COLOR});
% %         plotPSTH(unit.id, unit.neuronType, unit.layer, unit.ch, allTrialCount, {spikeTimeAlignedToBaselineVisStimHit, spikeTimeAlignedToBaselineVisStimMiss}, ... %spikeTimeAlignedToBaselineVisStimFa
% %             {fixedHoldStartsAtRelativeTrialHit, fixedHoldStartsAtRelativeTrialMiss}, ...
% %             {leverReleaseTimesAlignedToBaselineVisStimHit, leverReleaseTimesAlignedToBaselineVisStimMiss}, {}, PRE_TIME_VIS_STIM, POST_TIME_VIS_STIM, EDGES_VIS_STIM, ...
% %             'Baseline Stim aligned (Lever Release blue marked)', 'Baseline Stim aligned', 'baselineStimAligned', {'Hit','Miss'}, {'b'}, {HIT_COLOR, MISS_COLOR}); % 'Fa',
%         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% PSTHs %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

        % CHECK SHIFT IN TIME

%         plotPSTHToCheckShift(unit.id, unit.neuronType, unit.layer, unit.ch, allTrialCount, spikeTimeAlignedToLeverHoldAll, fixedHoldStartsAtRelativeTrialAll, targetVisStimAlignedToLeverHoldAll, ...
%             PRE_TIME_HOLD, POST_TIME_HOLD, EDGES_HOLD, 'Lever Hold aligned', 'leverHoldAligned', 'All', {'b', 'r'});
%         plotPSTHToCheckShift(unit.id, unit.neuronType, unit.layer, unit.ch, allTrialCount, spikeTimeAlignedToLeverHoldHit, fixedHoldStartsAtRelativeTrialHit, targetVisStimAlignedToLeverHoldHit, ...
%             PRE_TIME_HOLD, POST_TIME_HOLD, EDGES_HOLD, 'Lever Hold aligned', 'leverHoldAligned', 'Hit', {'b', 'r'});
%         plotPSTHToCheckShift(unit.id, unit.neuronType, unit.layer, unit.ch, allTrialCount, spikeTimeAlignedToLeverHoldFa, fixedHoldStartsAtRelativeTrialFa, targetVisStimAlignedToLeverHoldFa, ...
%             PRE_TIME_HOLD, POST_TIME_HOLD, EDGES_HOLD, 'Lever Hold aligned', 'leverHoldAligned', 'Fa', {'b', 'r'});
%         plotPSTHToCheckShift(unit.id, unit.neuronType, unit.layer, unit.ch, allTrialCount, spikeTimeAlignedToLeverHoldMiss, fixedHoldStartsAtRelativeTrialMiss, targetVisStimAlignedToLeverHoldMiss, ...
%             PRE_TIME_HOLD, POST_TIME_HOLD, EDGES_HOLD, 'Lever Hold aligned', 'leverHoldAligned', 'Miss', {'b', 'r'});
% 
%         plotPSTHToCheckShift(unit.id, unit.neuronType, unit.layer, unit.ch, allTrialCount, spikeTimeAlignedToLeverReleaseAll, fixedHoldStartsAtRelativeTrialAll, targetVisStimAlignedToLeverReleaseAll, ...
%             PRE_TIME_RELEASE, POST_TIME_RELEASE, EDGES_RELEASE, 'Lever Release aligned', 'leverReleaseAligned', 'All', {'b', 'r'});
%         plotPSTHToCheckShift(unit.id, unit.neuronType, unit.layer, unit.ch, allTrialCount, spikeTimeAlignedToLeverReleaseHit, fixedHoldStartsAtRelativeTrialHit, targetVisStimAlignedToLeverReleaseHit, ...
%             PRE_TIME_RELEASE, POST_TIME_RELEASE, EDGES_RELEASE, 'Lever Release aligned', 'leverReleaseAligned', 'Hit', {'b', 'r'});
%         plotPSTHToCheckShift(unit.id, unit.neuronType, unit.layer, unit.ch, allTrialCount, spikeTimeAlignedToLeverReleaseFa, fixedHoldStartsAtRelativeTrialFa, targetVisStimAlignedToLeverReleaseFa, ...
%             PRE_TIME_RELEASE, POST_TIME_RELEASE, EDGES_RELEASE, 'Lever Release aligned', 'leverReleaseAligned', 'Fa', {'b', 'r'});
%         plotPSTHToCheckShift(unit.id, unit.neuronType, unit.layer, unit.ch, allTrialCount, spikeTimeAlignedToLeverReleaseMiss, fixedHoldStartsAtRelativeTrialMiss, targetVisStimAlignedToLeverReleaseMiss, ...
%             PRE_TIME_RELEASE, POST_TIME_RELEASE, EDGES_RELEASE, 'Lever Release aligned', 'leverReleaseAligned', 'Miss', {'b', 'r'});
% 
%         plotPSTHToCheckShift(unit.id, unit.neuronType, unit.layer, unit.ch, allTrialCount, spikeTimeAlignedToTargetVisStimAll, fixedHoldStartsAtRelativeTrialAll, leverHoldTimesAlignedToTargetVisStimAll, ...
%             PRE_TIME_VIS_STIM, POST_TIME_VIS_STIM, EDGES_VIS_STIM, 'Target Stim aligned', 'targetStimAligned', 'All', {'b', 'r'});
%         plotPSTHToCheckShift(unit.id, unit.neuronType, unit.layer, unit.ch, allTrialCount, spikeTimeAlignedToTargetVisStimHit, fixedHoldStartsAtRelativeTrialHit, leverHoldTimesAlignedToTargetVisStimHit, ...
%             PRE_TIME_VIS_STIM, POST_TIME_VIS_STIM, EDGES_VIS_STIM, 'Target Stim aligned', 'targetStimAligned', 'Hit', {'b', 'r'});
%         plotPSTHToCheckShift(unit.id, unit.neuronType, unit.layer, unit.ch, allTrialCount, spikeTimeAlignedToTargetVisStimFa, fixedHoldStartsAtRelativeTrialFa, leverHoldTimesAlignedToTargetVisStimFa, ...
%             PRE_TIME_VIS_STIM, POST_TIME_VIS_STIM, EDGES_VIS_STIM, 'Target Stim aligned', 'targetStimAligned', 'Fa', {'b', 'r'});
%         plotPSTHToCheckShift(unit.id, unit.neuronType, unit.layer, unit.ch, allTrialCount, spikeTimeAlignedToTargetVisStimMiss, fixedHoldStartsAtRelativeTrialMiss, leverHoldTimesAlignedToTargetVisStimMiss, ...
%             PRE_TIME_VIS_STIM, POST_TIME_VIS_STIM, EDGES_VIS_STIM, 'Target Stim aligned', 'targetStimAligned', 'Miss', {'b', 'r'});
%         

        close all;
end
