%% rank_CircularDoGxCos_paramAspectRatio.m
clear; clc;

%% -----------------------------
% User inputs
%% -----------------------------
summaryFile = "DoGXCos_tau_summary.mat";   % change this
outPdf = "CircularDogxCos_ranked_sigmaS_vs_lambda.pdf";
outMat = "CircularDogxCos_ranked_sigmaS_vs_lambda.mat";
outCsv = "CircularDogxCos_ranked_sigmaS_vs_lambda.csv";

cellsPerPage = 50;
nRows = 5;
nCols = 10;

%% Load
S = load(summaryFile);
E = S.exportSummary;

%% Calculate aspect ratio
sigmaC = E.sigmaC(:);
deltaSigma = E.deltaSigma(:);
sigmaS = (sigmaC + deltaSigma) * 6;

f = E.f(:);                     % cycles/pixel
lambda = 1 ./ abs(f);           % pixels/cycle

aspectRatio = max(sigmaS, lambda) ./ min(sigmaS, lambda);
%% Frequency threshold
freqThresh = 6 * sigmaC;   % cycles/pixel
freqValid = abs(lambda) <= freqThresh;

valid = isfinite(aspectRatio) & ...
        isfinite(E.R2(:)) & ...
        sigmaS > 0 & ...
        lambda > 0 & ...
        abs(f) > 0 & ...
        freqValid;

validIdx = find(valid);

%% Sort ascending
[sortedAR, orderLocal] = sort(aspectRatio(valid), "ascend");
sortIdx = validIdx(orderLocal);

%% Save table
T = table( ...
    (1:numel(sortIdx))', ...
    E.cellIDs(sortIdx), ...
    sortedAR, ...
    E.R2(sortIdx), ...
    sigmaC(sortIdx), ...
    deltaSigma(sortIdx), ...
    sigmaS(sortIdx), ...
    f(sortIdx), ...
    lambda(sortIdx), ...
    E.DSI(sortIdx), ...
    E.OSI(sortIdx), ...
    E.F1F0(sortIdx), ...
    E.dataOriDeg(sortIdx), ...
    E.fftDeg(sortIdx), ...
    E.envDeg(sortIdx), ...
    E.offsetDeg(sortIdx), ...
    'VariableNames', { ...
        'Rank', ...
        'CellID', ...
        'AspectRatio_sigmaS_vs_lambda', ...
        'R2', ...
        'SigmaC', ...
        'DeltaSigma', ...
        'SigmaS', ...
        'Freq_cyclesPerPixel', ...
        'Lambda_pixelsPerCycle', ...
        'DSI', ...
        'OSI', ...
        'F1F0', ...
        'DataOriDeg', ...
        'FftDeg', ...
        'EnvDeg', ...
        'OffsetDeg'} ...
);

disp(T);

E.aspectRatio_sigmaS_vs_lambda = aspectRatio;
E.lambda_pixelsPerCycle = lambda;
E.aspectRatio_sortIdx = sortIdx;
E.aspectRatio_rankTable = T;

save(outMat, "E", "T");
writetable(T, outCsv);

%% Export ordered model fits
if exist(outPdf, "file")
    delete(outPdf);
end

nRanked = numel(sortIdx);
nPages = ceil(nRanked / cellsPerPage);

for page = 1:nPages

    pageStart = (page - 1) * cellsPerPage + 1;
    pageEnd = min(page * cellsPerPage, nRanked);
    pageRange = pageStart:pageEnd;

    fig = figure("Color", "w", "Position", [100 100 1800 1000]);

    for k = 1:numel(pageRange)

        idx = sortIdx(pageRange(k));

        subplot(nRows, nCols, k);

        if iscell(E.modelRF)
            RF = E.modelRF{idx};
        else
            RF = E.modelRF(:, :, idx);
        end

        imagesc(RF);
        axis image off;
        colormap(gca, gray);

        title(sprintf("Rank %d | Cell %d\nAR %.2f | R2 %.2f", ...
            pageRange(k), ...
            E.cellIDs(idx), ...
            aspectRatio(idx), ...
            E.R2(idx)), ...
            "FontSize", 7);
    end

    sgtitle(sprintf("Circular DoG x Cos ranked by max(sigmaS, lambda)/min(sigmaS, lambda) | Page %d/%d", ...
        page, nPages), ...
        "FontSize", 14);

    exportgraphics(fig, outPdf, ...
        "Append", true, ...
        "ContentType", "image", ...
        "Resolution", 200);

    close(fig);
end

fprintf("Saved PDF: %s\n", outPdf);
fprintf("Saved MAT: %s\n", outMat);
fprintf("Saved CSV: %s\n", outCsv);