
global atLab PRE_TIME_HOLD POST_TIME_HOLD PRE_TIME_RELEASE POST_TIME_RELEASE PRE_TIME_VIS_STIM POST_TIME_VIS_STIM ...
MIN_BIN_COUNT MAX_BIN_COUNT BIN_SIZE_PSTH EDGES_HOLD EDGES_RELEASE EDGES_VIS_STIM NEURON_TYPE_MFB NEURON_TYPE_SS NEURON_TYPE_CS NEURON_TYPE_MLI NEURON_TYPE_GoC NEURON_TYPE_DCN NEURON_TYPE_OTHER NEURON_TYPES ...
globalX globalY globalW globalH SMOOTH_TYPE SMOOTH_TYPE_L SPIKE_SPAN SPAN_NARROW PLOT_FONT_SIZE PRINT_FONT_SIZE ALL_COLOR HIT_COLOR FA_COLOR MISS_COLOR RANDOM_COLOR FIXED_COLOR ...
PRE_WINDOW_RESPONSE_PROP PERI_WINDOW_RESPONSE_PROP RESPONSE_INCREASING RESPONSE_DECREASING RESPONSE_NO_CHANGE_OR_MIXED ...
COLOR_CODE_MF COLOR_CODE_SS COLOR_CODE_CS COLOR_CODE_DCS COLOR_CODE_BC_SC COLOR_CODE_GoC COLOR_CODE_UBC COLOR_CODE_UNKNOWN COLOR_CODES COLOR_CODES_PLT


localPath = fileparts(which(matlab.desktop.editor.getActiveFilename));
if ispc % If the OS is Windows
    pattern = '\';
else
    pattern = '/';
end
inds = strfind(localPath,pattern);
addpath(genpath(localPath(1:inds(length(inds))-1)))

globalX = 800; % 4000
globalY = 150;
globalW = 1500; 
globalH = 1500;

atLab = 1;

if atLab
    globalX = 4000;
    globalY = 150; %200;
else
    globalX = 1000; % 4000
    globalY = -150; %150;
end

PLOT_FONT_SIZE = 15;  
PRINT_FONT_SIZE = 30;
%PLOT_FONT_SIZE = PRINT_FONT_SIZE;

ALL_COLOR = 'k';
HIT_COLOR = 'b';
FA_COLOR = 'r';
MISS_COLOR = 'm';

RANDOM_COLOR = "#D95319"; % Orange
FIXED_COLOR = "#77AC30"; % Green

PRE_TIME_HOLD = 1; %1; %0.5;%  % (s) pre-stimulus duration to include
POST_TIME_HOLD = 2; %1; %1.5; % (s) post-stimulus duration to include
PRE_TIME_RELEASE = .5; %1; %1; % (s) pre-stimulus duration to include
POST_TIME_RELEASE = 1.5; %1; %1; % (s) post-stimulus duration to include
PRE_TIME_VIS_STIM = 1; %1;
POST_TIME_VIS_STIM = 1; %1;

PRE_WINDOW_RESPONSE_PROP = [-1 -.5];
PERI_WINDOW_RESPONSE_PROP = [-.5 1];
RESPONSE_INCREASING = 1;
RESPONSE_DECREASING = -1;
RESPONSE_NO_CHANGE_OR_MIXED = 0;

MIN_BIN_COUNT = 10;
MAX_BIN_COUNT = 150;
BIN_SIZE_PSTH = 0.005; % sec = 2 ms
EDGES_HOLD = -PRE_TIME_HOLD-BIN_SIZE_PSTH:BIN_SIZE_PSTH:POST_TIME_HOLD+BIN_SIZE_PSTH;
EDGES_RELEASE = -PRE_TIME_RELEASE-BIN_SIZE_PSTH:BIN_SIZE_PSTH:POST_TIME_RELEASE+BIN_SIZE_PSTH;
EDGES_VIS_STIM = -PRE_TIME_VIS_STIM-BIN_SIZE_PSTH:BIN_SIZE_PSTH:POST_TIME_VIS_STIM+BIN_SIZE_PSTH;

NEURON_TYPE_MFB = 'MFB';
NEURON_TYPE_SS = 'PkC ss';
NEURON_TYPE_CS = 'PkC cs';
NEURON_TYPE_MLI = 'MLI';
NEURON_TYPE_GoC = 'GoC';
NEURON_TYPE_DCN = 'DCN';
NEURON_TYPE_OTHER = '';

NEURON_TYPES = {NEURON_TYPE_MFB, NEURON_TYPE_SS, NEURON_TYPE_CS, NEURON_TYPE_MLI, NEURON_TYPE_GoC, NEURON_TYPE_OTHER};

% NEURON_TYPE_MF = 'MF';
% NEURON_TYPE_SS = 'PC SS';
% NEURON_TYPE_CS = 'PC CS';
% NEURON_TYPE_DCS = 'PC DCS';
% NEURON_TYPE_BC_SC = 'BC or SC';
% NEURON_TYPE_GoC = 'GoC';
% NEURON_TYPE_UBC = 'UBC';
% NEURON_TYPE_UNKNOWN = 'Unknown';
% 
% NEURON_TYPES = {NEURON_TYPE_MF, NEURON_TYPE_SS, NEURON_TYPE_CS, NEURON_TYPE_DCS, NEURON_TYPE_BC_SC, NEURON_TYPE_GoC, NEURON_TYPE_UBC, NEURON_TYPE_UNKNOWN};

COLOR_CODE_MF = [0 0 1 0.7]; % Blue
COLOR_CODE_SS = [1 0 0 0.7]; % Red
COLOR_CODE_CS = [0 1 0 0.7]; % Green
COLOR_CODE_DCS = [0.5 1 1 0.7]; % Cyan
COLOR_CODE_BC_SC = [0.8500 0.3250 0.0980 0.7]; % Orange
COLOR_CODE_GoC = [1 0 1 0.7]; % Magenta
COLOR_CODE_UBC = [.9 .9 .9 0.7]; % Grey
COLOR_CODE_UNKNOWN = [0 0 0 0.7]; % Black

COLOR_CODES = {COLOR_CODE_MF, COLOR_CODE_SS, COLOR_CODE_CS, COLOR_CODE_DCS, COLOR_CODE_BC_SC, COLOR_CODE_GoC, COLOR_CODE_UBC, COLOR_CODE_UNKNOWN};

SMOOTH_TYPE = 'rlowess';
SMOOTH_TYPE_L = 'lowess';
SPIKE_SPAN = .07; %0.01;

SPAN_NARROW = 0.2;

% have as many colors as recording days
COLOR_CODES_PLT = {[0 0 1], [1 0 0], [0 1 0], [0.8500 0.3250 0.0980], [1 1 1]};