
global atLab PRE_TIME_HOLD POST_TIME_HOLD PRE_TIME_RELEASE POST_TIME_RELEASE PRE_TIME_VIS_STIM POST_TIME_VIS_STIM ...
BIN_SIZE_PSTH EDGES_HOLD EDGES_RELEASE EDGES_VIS_STIM NEURON_TYPE_MF NEURON_TYPE_SS NEURON_TYPE_CS NEURON_TYPE_DCS NEURON_TYPE_BC_SC NEURON_TYPE_GoC NEURON_TYPE_UBC NEURON_TYPE_UNKNOWN NEURON_TYPES ...
globalX globalY globalW globalH SMOOTH_TYPE SMOOTH_TYPE_L SPIKE_SPAN SPAN_NARROW PLOT_FONT_SIZE ALL_COLOR HIT_COLOR FA_COLOR MISS_COLOR RANDOM_COLOR FIXED_COLOR ...
PRE_WINDOW_RESPONSE_PROP PERI_WINDOW_RESPONSE_PROP RESPONSE_INCREASING RESPONSE_DECREASING RESPONSE_NO_CHANGE_OR_MIXED

localPath = fileparts(which(matlab.desktop.editor.getActiveFilename));
if ispc % If the OS is Windows
    pattern = '\';
else
    pattern = '/';
end
inds = strfind(localPath,pattern);
addpath(genpath(localPath(1:inds(length(inds))-1)))

globalX = 1000; % 4000
globalY = 150;
globalW = 900; 
globalH = 900;

atLab = 1;

if atLab
    globalX = 4000;
    globalY = -150; %200;
else
    globalX = 1000; % 4000
    globalY = -150; %150;
end

PLOT_FONT_SIZE = 15;
ALL_COLOR = 'k';
HIT_COLOR = 'b';
FA_COLOR = 'r';
MISS_COLOR = 'm';

RANDOM_COLOR = "#D95319"; % Orange
FIXED_COLOR = "#77AC30"; % Green

PRE_TIME_HOLD = 1; %1; %0.5;%  % (s) pre-stimulus duration to include
POST_TIME_HOLD = 2; %1; %1.5; % (s) post-stimulus duration to include
PRE_TIME_RELEASE = .5; %1; %1; % (s) pre-stimulus duration to include
POST_TIME_RELEASE = .5; %1; %1; % (s) post-stimulus duration to include
PRE_TIME_VIS_STIM = 1; %1;
POST_TIME_VIS_STIM = 1; %1;

PRE_WINDOW_RESPONSE_PROP = [-1 -.5];
PERI_WINDOW_RESPONSE_PROP = [-.5 1];
RESPONSE_INCREASING = 1;
RESPONSE_DECREASING = -1;
RESPONSE_NO_CHANGE_OR_MIXED = 0;

BIN_SIZE_PSTH = 0.005; % sec = 2 ms
EDGES_HOLD = -PRE_TIME_HOLD-BIN_SIZE_PSTH:BIN_SIZE_PSTH:POST_TIME_HOLD+BIN_SIZE_PSTH;
EDGES_RELEASE = -PRE_TIME_RELEASE-BIN_SIZE_PSTH:BIN_SIZE_PSTH:POST_TIME_RELEASE+BIN_SIZE_PSTH;
EDGES_VIS_STIM = -PRE_TIME_VIS_STIM-BIN_SIZE_PSTH:BIN_SIZE_PSTH:POST_TIME_VIS_STIM+BIN_SIZE_PSTH;

NEURON_TYPE_MF = 'MF';
NEURON_TYPE_SS = 'PC SS';
NEURON_TYPE_CS = 'PC CS';
NEURON_TYPE_DCS = 'PC DCS';
NEURON_TYPE_BC_SC = 'BC or SC';
NEURON_TYPE_GoC = 'GoC';
NEURON_TYPE_UBC = 'UBC';
NEURON_TYPE_UNKNOWN = 'Unknown';

NEURON_TYPES = {NEURON_TYPE_MF, NEURON_TYPE_SS, NEURON_TYPE_CS, NEURON_TYPE_DCS, NEURON_TYPE_BC_SC, NEURON_TYPE_GoC, NEURON_TYPE_UBC, NEURON_TYPE_UNKNOWN};

SMOOTH_TYPE = 'rlowess';
SMOOTH_TYPE_L = 'lowess';
SPIKE_SPAN = .07; %0.01;

SPAN_NARROW = 0.2;
